### ISSUE TITLE
Security Breach. 

### ISSUE THREAD

**Issue by sanjaypradeep** [hackstarsj/DjangoMedicalStoreFrontEndInReactJS#1]
![image](https://user-images.githubusercontent.com/18122757/90279204-5e760c00-de86-11ea-9b3a-96ef78cd4981.png)

**Comment by sanjaypradeep** [comment]
User credentials can be captured from the request sent.

**Comment by hackstarsj** [comment]
Forked the project and make it secure because i didn't work on security of
this project yet this is just learning purpose purpose and don't use in
production

**Comment by hackstarsj** [comment]
A more better clarification for your problem

https://stackoverflow.com/questions/47122923/how-to-send-password-in-encrypted-form-from-reactjs-to-expressjs
